name: Github CI build

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
env:
  RELEASE: 5.0.0.43

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare
      run: mkdir output

    - name: Build aarch64
      id: build_aarch64
      uses: coderus/github-sfos-build@sfos5
      with:
        release: ${{ env.RELEASE }}
        arch: noarch
      
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: output-rpms
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        gh release create "$tag_name" "${assets[@]}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
